### ISSUE TITLE
SPD2010触摸相关寄存器手册

### ISSUE THREAD

**Issue by modi12jin** [lihao4732/gitTest#1]
@lihao4732 你好！打扰一下，你有SPD2010触摸相关寄存器手册吗？我在分销商哪里没有获取到。
通过I2C扫描，知道SPD2010地址0x53或者0xD3，没有触摸相关寄存器，工作无法进行。
如果你有，可以提供给我吗？我将不甚感激！！！

**Comment by lihao4732** [comment]
只有这两份文档，不知道对你有没有用，具体协议可能还是要看原厂如何定义的。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月25日 16:17 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [lihao4732/gitTest] SPD2010触摸相关寄存器手册 (Issue #1) |

Closed #1 as completed.

**Comment by modi12jin** [comment]
@lihao4732 我没看到你发送的附件文档，你能告诉我文档在那里？

这是我使用屏幕
https://github.com/Lzw655/esp32-s3-lcd-ev-baord-docs/issues/3

**Comment by lihao4732** [comment]
推git仓库了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月25日 21:29 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [lihao4732/gitTest] SPD2010触摸相关寄存器手册 (Issue #1) |

@lihao4732 我没看到你发送的附件文档，你能告诉我文档在那里？

这是我使用屏幕
Lzw655/esp32-s3-lcd-ev-baord-docs#3

**Comment by modi12jin** [comment]
非常感谢！谢谢你的提示
